version: '3.8'
services:
  app:
    build: .
    ports:
      - "7000:7000"
    volumes:
      - .:/app
      - ./config.yml:/app/config.yml
      - ./models:/app/models
      - ${HF_CACHE_DIRECTORY}:/root/.cache/huggingface
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - PORT=7000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    env_file:
      - .env